name: spotify_copy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  audio_service: ^0.18.13
  equatable: ^2.0.5
  just_audio: ^0.9.37
  built_value: ^8.9.0
  uuid: ^4.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  cloud_firestore: ^4.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  built_value_generator: ^8.8.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
